language:
  - php

php:
  - 7.2

install:
  - composer require --dev phpunit/phpunit

script:
  - phpunit tests/tnaNewsletterTest.php

notifications:
  slack:
    rooms:
      - tna-digital:C2GnodnLsxhwwGvr0xAcajzc#code-builds
