language:
  - php
  - node_js

php:
  - 5.6

node_js:
  - 4.4.5

install:
  - composer require --dev phpunit/phpunit

script:
  - phpunit tests/tnaNewsletterTest.php

notifications:
  slack:
    rooms:
      - tna-digital:C2GnodnLsxhwwGvr0xAcajzc#code-builds
